#define SHUTDOWN_TIMEOUT_IN_SECOUNDS 120
#define MIN_VOLUME 1
#define MAX_VOLUME 20
#define INITIAL_VOLUME 5

#define PIN_PAUSE_BUTTON A0
#define PIN_NEXT_BUTTON A1
#define PIN_PREV_BUTTON A2

#define PIN_SHUTDOWN A3

#define PIN_VOLUME_UP_BUTTON A4
#define PIN_VOLUME_DOWN_BUTTON A5
